# Generated by Django 5.2.1 on 2025-07-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_add_company_auth_fields'),
        ('server', '0005_company_created_at_company_password_and_more'),
    ]

    operations = [
    ]
